### ISSUE TITLE
Calendar does not show on device; works in simulator

### ISSUE THREAD

**Issue by tomconte** [pec1985/Calendar-View-for-Appcelerator-v2#1]
The calendar works fine in the simulator, but when I run the app on a real device, it does not show up. The month labels are OK, as well as the current month/year, but the grid is not displayed.
I guess the problem lies somewhere in the JavaScript in calendar/index.html, but how can I debug that?

**Comment by pec1985** [comment]
I don't know, to be honest. I built this over a year ago using Ti SDK 1.4 and a lot of things have changed. When I have time I'll revisit this project and fix the issues that I may encounter.

You may want to start looking at the path of the png files. That has changed in the platform since then.
